### ISSUE TITLE
Remove project path from python path.

### ISSUE THREAD

**Issue by jmfederico** [frostming/pdm#105]
Before explaining my request, please see the output of `sys.path` on macOS with pdm verison 0.7.0 and python installed from official python.org installers:

```python
['',
 '/path/to/project/__pypackages__/3.8/lib',
 '/path/to/project',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload']
```

I think that item 3 (index 2) should not exist. The root of your project where pyproject.toml is located should not be assumed to be part of the user's desired search paths.

In a scenario where the project is:

```tree
. # /path/to/project/
+-- pryproject.toml
+-- src
|   +-- module_a.py
|   +-- module_b.py
+-- package_a
    +-- module_c.py
```

When a user runs `pdm run python` from the `src`, the parent path would be included in the search path list, which is not standard or expected behavior.

The user chooses what the current working directory is by executing python in the desired path, and can use `PYTHONPATH` to add extra paths.

My proposal is for sys.path to be:
```python
['',
 '/path/to/project/__pypackages__/3.8/lib',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
 '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload']
```

Thanks

**Comment by frostming** [comment]
Tested with the same structure, I got:
```
['',
 'D:\\Workspace\\pdm-test\\__pypackages__\\3.7\\lib',
 'd:\\workspace\\pdm-test\\src',
 'D:\\Programs\\Python\\Python37\\python37.zip',
 'D:\\Programs\\Python\\Python37\\DLLs',
 'D:\\Programs\\Python\\Python37\\lib',
 'D:\\Programs\\Python\\Python37'
]
```
Note the 3rd item. It is injected by the editable installation file at `__pypackage__/X.Y/lib/easy-install.pth`. PDM will try to install the current working directory as an editable package, so the package path will be added into the sys.path. And this package follows a `src` package dir convention.

In your example, you have two such directories. It is not a typical library structure and I guess you don't want it to be a **library**. In this case, you can remove the `name` and `version` from `pyproject.toml`, and PDM won't install it as an editable package. Don't forget to clear `__pypackages__/X.Y/lib/` folder before re-installation.

**Comment by jmfederico** [comment]
You are right, this is not a **library**.

To clarify, with pdm:
- If I have a version and a name in my pyproject.toml, pdm install my project as an editable package.
- With no name or version, pdm will not install my project as an editable package.

Correct?

**Comment by frostming** [comment]
Correct, the editable installation works in the way that it puts a `.pth` file under library root, which contains the package path, and the path will in turn be loaded when Python starts up.

**Comment by jmfederico** [comment]
Had not noticed the `.pth` file.
