### ISSUE TITLE
A change in resolvelib broke pdm

### ISSUE THREAD

**Issue by jmfederico** [frostming/pdm#118]
The following change in resolvelib breaks the monkeypatching done by pdm:

https://github.com/sarugaku/resolvelib/commit/eeceaf69ba83926a5c47813b06d9033e161eeb74#diff-9d16b368db940f0b65c2b9b5ba4d6ed3R71

When resolving dependencies the following error is thrown:
`[TypeError]: adding_requirement() missing 1 required positional argument: 'parent'`

Problem in pdm:

https://github.com/frostming/pdm/blob/927e4957360a28564a8246088c865135ccb3a784/pdm/resolver/core.py#L19

## How to reproduce:

Make a clean install of pdm with newest dependencies updated: **resolvelib version 0.4.0**
Try to add any dependency to a project with pdm: `pdm add ...`

**Comment by frostming** [comment]
Already working on it, thanks for the report
