### ISSUE TITLE
如何与现有 Python 库一起使用？

### ISSUE THREAD

**Issue by abersheeran** [frostming/pdm#128]
很多 Python 库都可以指定虚拟环境来寻找项目需要的库。

以 uwsgi 为例，可以通过 virtualenv 选项指定环境。

```ini
[uwsgi]
...
virtualenv = venv
...
```

在同一台电脑上的多个不同项目，如何告诉诸如 uwsgi 的程序分别去指定的目录找依赖？

我看了文档和命令，没有提到这一点。

**Comment by frostming** [comment]
UWSGI的`virtualenv`/`home`配置相当于是修改了`PYTHONHOME`的值，这会影响`sys.prefix`.
PEP582/PDM并不存在这么一个HOME的概念，它只隔离包，不是隔离解释器。所以对应的方法是
```bash
export PYTHONPATH=/path/to/__pypackages__/3.8/lib:$PYTHONPATH
```
试试看这个

**Comment by abersheeran** [comment]
懂了，这个设计很有趣。不过文档里没提，建议写一写关于这个的文档。
