### ISSUE TITLE
Built wheels cache never hit

### ISSUE THREAD

**Issue by frostming** [frostming/pdm#200]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```bash
$ pdm add pyrsistent
```
Then reinstall it:
```bash
$ rm -rf __pypackages__ && pdm install
```

## Actual behavior

The wheels are built twice

## Expected behavior

Should reuse the built wheel in the first step.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```

**Comment by songololo** [comment]
Curious if this is still an issue, I'm noticing on my system that `pyrsistent` is taking ages to resolve each time I try to add a package via PDM.
