### ISSUE TITLE
Resolution result is wrong for docutils

### ISSUE THREAD

**Issue by frostming** [frostming/pdm#21]
## Reproduce

`pdm add "docutils<0.16,>=0.10"`

## Expected

`docutils==0.15.2`

## Actual
```toml
[[package]]
name = "docutils"
sections = ["default"]
version = "0.15.post1"
marker = "python_version >= \"2.6\" and python_version not in \"3.0, 3.1, 3.2\""
summary = "Docutils -- Python Documentation Utilities"

[metadata]
"docutils 0.15.post1" = [
    {file = "docutils-0.15.post1-py2-none-any.whl", hash = "sha256:ba4584f9107571ced0d2c7f56a5499c696215ba90797849c92d395979da68521"},
]

[root]
content_hash = "md5:a34a70283dc33a99743b6086bef07c0f"
meta_version = "0.0.1"

```

**Comment by jamestansx** [comment]
Hi, should this issue be reopened? 

---
# Reproduce

1. pdm venv create -n kivy_venv
2. activate venv
3. pdm add kivy[base]
4. Error occurred
This is the detailed trackback: [pdm-lock-y2phrkl8.log](https://github.com/pdm-project/pdm/files/6818468/pdm-lock-y2phrkl8.log)

Trying to add ```docutils```:

1. pdm add docutils
2. Error occured
Details: [pdm-lock-k0g4mvly.log](https://github.com/pdm-project/pdm/files/6818476/pdm-lock-k0g4mvly.log)

**Comment by frostming** [comment]
Can you show the pyproject.toml? It is not clear why 0.15.1 is picked

**Comment by jamestansx** [comment]
pyproject.toml

````markdown
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "James Tan", email = "jamestansx@gmail.com"},
]
dependencies = []
requires-python = "<=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"


[tool]
[tool.pdm]
````

**Comment by frostming** [comment]
`<=3.9` is just too wide IMHO. At least restrict to `>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*,<=3.9`

**Comment by jamestansx** [comment]
> <=3.9 is just too wide IMHO. At least restrict to >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<=3.9

Ya, this is the problem. Now I have restricted it to ```>=3.6,<=3.9``` and it works. 
Thanks! and sorry for reporting not useful issue.
