### ISSUE TITLE
pdm publish command

### ISSUE THREAD

**Issue by frostming** [frostming/pdm#22]

**Comment by pawamoy** [comment]
Just saw that there's no publish command. Did you remove it on purpose? I can't read what's in #229 :sweat_smile:

**Comment by frostming** [comment]
@pawamoy Thanks for comming here. This idea is rejected as it doesn't gain much. You can always achieve this in one command line:
```bash
$ pdm build && twine upload dist/*
```
And have `twine` installed globally instead of bundled with `pdm` looks neater to me.

**Comment by frostming** [comment]
Since it isn't much related to other parts of PDM, you can make a plugin to add a `publish` command to PDM. If you are interested you can start from [here](https://pdm.fming.dev/plugin/)

**Comment by pawamoy** [comment]
Fair enough! It was easy to make the change in my template, `twine upload --skip-existing dist/*` instead of `pdm publish`so I'll use twine for now 🙂 
Also, I agree, not having to deal with authentication against indexes in PDM itself surely makes it easier to maintain!

**Comment by branchvincent** [comment]
I also wanted this so I created a simple [`publish` plugin](https://github.com/branchvincent/pdm-publish), which just wraps twine. feel free to try it out!

**Comment by frostming** [comment]
@branchvincent that is great and how the plugin system should work. I am going to create an "awesome" project to list your excellent work someday.
