### ISSUE TITLE
pdm info输出改进/新的子命令

### ISSUE THREAD

**Issue by WAY29** [frostming/pdm#224]
pdm info说的是Show the project information,但是当我输入pdm info的时候我只拿到了
```
PDM version:        1.1.0
Python Interpreter: F:/Python/python.exe (3.7.3)
Project Root:       F:/NEW_WORKON/example
```
在我想象中我觉得输出pyproject.toml中的信息会更好

另外能否添加一个新的子命令用于更改pyproject.toml中的值?

**Comment by frostming** [comment]
我希望功能不冗余，`pdm info`更多的是关于本项目pdm相关的执行信息
如果是pyproject.toml完全可以`cat pyproject.toml`，甚至还能语法高亮

更改值的话，值分各种类型，还有array 和 dict类型，这样的话不如大家自己在编辑器里改？

意下如何

**Comment by frostming** [comment]
如果有兴趣可以贡献一个插件，我很乐意加到插件列表里面

**Comment by WAY29** [comment]
> 我希望功能不冗余，`pdm info`更多的是关于本项目pdm相关的执行信息
> 如果是pyproject.toml完全可以`cat pyproject.toml`，甚至还能语法高亮
> 
> 更改值的话，值分各种类型，还有array 和 dict类型，这里的增删查改就要好好设计CLI接口了，这样的话不如大家自己在编辑器里改？
> 
> 意下如何

我发现其实我是需要一个更新pyproject中version的值的功能,就比如说在build的时候?

**Comment by frostming** [comment]
这一块已经有非常成熟的工具，[bumpversion](https://github.com/c4urself/bump2version/#installation)，pdm同样不想费力集成进来，不过插件形式是可以的。现在pdm内置支持的version指定方法有

1. `version = "0.1.0"` 硬编码，这种可以配合`bumpversion`一起用
2. `version = {from = "mypackage/__init__.py"}` 从文件中读取`__version__`的值
3. `version = {use_scm = true}` 版本号跟随git tag 一起走。

**Comment by WAY29** [comment]
> 这一块已经有非常成熟的工具，[bumpversion](https://github.com/c4urself/bump2version/#installation)，pdm同样不想费力集成进来，不过插件形式是可以的。现在pdm内置支持的version指定方法有
> 
> 1. `version = "0.1.0"` 硬编码，这种可以配合`bumpversion`一起用
> 2. `version = {from = "mypackage/__init__.py"}` 从文件中读取`__version__`的值
> 3. `version = {use_scm = true}` 版本号跟随git tag 一起走。

好的 谢谢你的解答 还是吃过的盐不够多(
