### ISSUE TITLE
Strategy to use ~= operator

### ISSUE THREAD

**Issue by uranusjr** [frostming/pdm#225]
## Is your feature request related to a problem? Please describe.

Currently pdm uses a `<,>=` syntax for the compatible version strategy. Most of the time, the version range can be written much more concisely with `~=`. For example, the only difference between `<5,>=4.2.1` and `~=4.2` is `4.2.1`, which does not matter most of the time, being a patch release.

## Describe the solution you'd like

The naming may be problematic. pdm calls the `<,>=` strategy “compatible”, but `~=` is actually called the *compatible release operator* in PEP 440. So either pdm needs to invent something new for `~=` (and potentially causes confusion to standard packaging), or change the name for `<,>=`.

**Comment by frostming** [comment]
A minor behavior change from `<5,>=4.2.1` to `~=4.2` does little harm I think?

**Comment by uranusjr** [comment]
I wouldn’t care at all personally, at least 🙂
