### ISSUE TITLE
How to write a pdm plugin?

### ISSUE THREAD

**Issue by WAY29** [frostming/pdm#227]
我已经查看了[doc中关于plugin](https://pdm.fming.dev/plugin/)中的内容
但是似乎缺乏了如何使插件生效/测试插件的演示...

**Comment by frostming** [comment]
publish了以后别人只要 `pip install pdm-plugin` （在和`pdm`相同的环境中）就自动生效

**Comment by WAY29** [comment]
> publish了以后别人只要 `pip install pdm-plugin` （在和`pdm`相同的环境中）就自动生效

明白了 但是这样的话在本地测试有点麻烦(需要不断build install)

**Comment by frostming** [comment]
补充了一点文档

> 但是这样的话在本地测试有点麻烦(需要不断build install)

可以`pip install -e pdm-plugin`

**Comment by WAY29** [comment]
> 补充了一点文档
> 
> > 但是这样的话在本地测试有点麻烦(需要不断build install)
> 
> 可以`pip install -e .`(`.`是当前开发插件的项目目录)


使用`pip -e`我会遇到以下问题
```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: path
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

**Comment by frostming** [comment]
hmm, 按道理PEP 582 自动加载可解
这里有关于如何启用
https://pdm.fming.dev/#enable-pep-582-globally

**Comment by WAY29** [comment]
> hmm, 按道理PEP 582 自动加载可解
> 这里有关于如何启用
> https://pdm.fming.dev/#enable-pep-582-globally
> 
> 启用之后只用在插件项目中执行：`pdm install -d`，然后在本项目中 pdm是启用了插件的状态，出去就不是

非常感谢你的帮助 :(我觉得可以把这点写在文档里让更多人知道
