### ISSUE TITLE
pdm publish子命令

### ISSUE THREAD

**Issue by WAY29** [frostming/pdm#229]
事实上我正在尝试编写一个pdm-publish的插件来为pdm添加发布到pypi的功能(就像poetry一样),但这似乎违反了pdm的初衷?同时我在编写的过程中遇到了许多麻烦,比如网上能搜到的方法几乎都是使用twine进行上传,而twine似乎没有暴露良好的api方便调用
所以我想问的是
- 我的能力似乎有点不足,作者有没有想过这方面的计划?
- 是否有必要编写这样的一个插件?还是继续使用`pdm build && twine upload dist/*`?

**Comment by frostming** [comment]
> 事实上我正在尝试编写一个pdm-publish的插件来为pdm添加发布到pypi的功能(就像poetry一样),但这似乎违反了pdm的初衷

不会，做插件丰富功能完全可以，只要这个插件有利于效率的提升

> 而twine似乎没有暴露良好的api方便调用

不见得，upload的主入口在这
https://github.com/pypa/twine/blob/534385596820129b41cbcdcc83d34aa8788067f1/twine/commands/upload.py#L77

> 我的能力似乎有点不足,作者有没有想过这方面的计划?

暂时没有

> 是否有必要编写这样的一个插件?还是继续使用pdm build && twine upload dist/*?

如果你感到困难，你可以继续使用`twine`，如你所见，这个命令也很简单不是吗，你可以加到`scripts`快捷方式里面: https://pdm.fming.dev/project/#run-scripts-in-isolated-environment
