### ISSUE TITLE
build子命令添加--no-pypkg 参数

### ISSUE THREAD

**Issue by WAY29** [frostming/pdm#233]
pdm打包时会将__pypackage__文件夹打包进去,而当使用pip安装wheel时pip又会从网上下载项目所需的依赖,这导致__pypackage__完全没有作用,而且会大大增大打包大小,是否应该增加一个--no-pypkg参数使得pdm打包时不将该文件夹打包进去?

**Comment by frostming** [comment]
这是bug不是enhancement, 请升级`pdm-pep517`看看是否问题已解决

**Comment by WAY29** [comment]
> 这是bug不是enhancement, 请升级`pdm-pep517`看看是否问题已解决

问题似乎已经解决
