### ISSUE TITLE
Mention in the docs, that `pdm add -e <package>` is available

### ISSUE THREAD

**Issue by pohlt** [frostming/pdm#241]
## Is your feature request related to a problem? Please describe.

When I quickly tried to figure out if pdm ticks all the boxes, I could not find any information about installing packages editable.

## Describe the solution you'd like

Somewhere in the docs, `pdm add -e <package>` could be mentioned.

**Comment by frostming** [comment]
Wanna contribute to the documentation? Welcome

**Comment by pohlt** [comment]
Sure. #242
