### ISSUE TITLE
Cryptic error message trying to import git URL requirement

### ISSUE THREAD

**Issue by LewisGaul** [frostming/pdm#245]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Create `requirements.txt` file with a git URL requirement and run `pdm import requirements.txt`.

## Actual behavior

```
$cat requirements.txt
git+https://github.com/LewisGaul/sanic-oauth@v0.4.1

$pdm -v import requirements.txt
[AttributeError]: 'NoneType' object has no attribute 'name'
```

## Expected behavior

Requirement to be added to `pyproject.toml`, or an error message explaining what went wrong and/or why this isn't supported.

## Environment Information

```
$pdm info && pdm info --env
PDM version:        1.2.0.post1
Python Interpreter: /usr/bin/python3.9 (3.9.0)
Project Root:       /home/legaul/tmp/proj-test
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.0c1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.4.0-19041-Microsoft",
  "platform_system": "Linux",
  "platform_version": "#488-Microsoft Mon Sep 01 13:43:00 PST 2020",
  "python_full_version": "3.9.0rc1",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
You should have a name part in the URL like this:
```
sanic-oauth @ git+https://github.com/LewisGaul/sanic-oauth@v0.4.1
```

**Comment by LewisGaul** [comment]
`pip install` doesn't seem to require that - is it something that could be added by `pdm import`?

**Comment by frostming** [comment]
PDM follows PEP 621 metadata while PEP 621 leverages PEP 508/PEP 440 to specify dependencies.

The name can't be determined until it is built. `pip install` allows that since it is not a strict PEP 508 follower.

**Comment by LewisGaul** [comment]
Ok that sounds reasonable (although I'm not up to speed on the details of the PEPs). I guess my next question/request is whether the error message in this (presumably mainline) situation could be improved?
```diff
- [AttributeError]: 'NoneType' object has no attribute 'name'
+ [PDMImportError]: Unable to import requirement 'git+https://github.com/LewisGaul/sanic-oauth@v0.4.1' which has no 'name'
+                   See ... for details of why this is required and how to fix the error
```

**Comment by frostming** [comment]
@LewisGaul Thanks for the feedback, I make a PR to build the package to find the project name.
