### ISSUE TITLE
Don't automatically add the current directory as a module

### ISSUE THREAD

**Issue by ksamuel** [frostming/pdm#253]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```bash
pdm add pendulum
```

## Actual behavior

```bash
user@computer ~/Noël/foo [1]$ pdm add pendulum
Adding packages to default dependencies: pendulum
✔ 🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 5 to add, 0 to update, 0 to remove

  ✔ Install pendulum 2.1.2 successful
  ✔ Install python-dateutil 2.8.1 successful
  ✔ Install pytzdata 2020.1 successful
  ✔ Install six 1.15.0 successful
Installing the project as an editable package...
  ✔ Install foo 0.0.0 successful

🎉 All complete!
 ```

This will install `foo` as a package because it's my project name, but my project may not be one:

- it may be a collection of scripts, with no `__init__.py`
- my main directory may be the project name, but it may contains a module, a package or a src directory that contains the stuff I want to install

## Expected behavior

I do think it's a great feature to have your code installed in dev mode. So many people don't know this mode exists and have PYTHONPATH problems because of this, especially with unit tests.

So I'm not sure what's the best behavior here. Maybe prompt what to do in init ?

**Comment by frostming** [comment]
If `pyproject.toml` doesn't have `name` field, then it won't be installed

> Maybe prompt what to do in init ?

Yes I am always thinking to do this way
