### ISSUE TITLE
Matrix Testing Support

### ISSUE THREAD

**Issue by danieleades** [frostming/pdm#259]
I've just started playing around with `PDM`, and it looks really, really impressive

I wanted to ask you about how thie library, or PEP 582 in general, can support a test workflow that involves testing against a matrix of Python/dependency versions.

For example-
- I have a project that claims to support a wide range of python versions *and* a wide version range of some key dependencies
- I would like to check that claim in CI by running the tests across multiple Python versions, and multiple versions of these key dependencies

bonus points for
- leaving the project in a clean state when testing is complete
- opportunities for parallelisation

How would I go about this using PDM?

I tend to prefer [Nox](https://nox.thea.codes/en/stable/) as a test runner, but that's not too important.

**Comment by frostming** [comment]
I just released PDM 1.4.0 and [tox-pdm](https://pypi.org/p/tox-pdm) 0.1.0 to address this problem.

If you are using GitHub Action or similar CI platforms, they provide a good way to run tests on a matrix of parameters. If that is not the case and you are running the testing locally or on a platform that is not that smart. I created tox-pdm that enhances Tox to use PDM as the package manager, get the README about how to use it.

I hope it helps.

**Comment by danieleades** [comment]
> I just released PDM 1.4.0 and [tox-pdm](https://pypi.org/p/tox-pdm) 0.1.0 to address this problem.
> 
> If you are using GitHub Action or similar CI platforms, they provide a good way to run tests on a matrix of parameters. If that is not the case and you are running the testing locally or on a platform that is not that smart. I created tox-pdm that enhances Tox to use PDM as the package manager, get the README about how to use it.
> 
> I hope it helps.

that looks like a really good solution!
again, personally i'm using Nox, but Tox seems to be used much more widely.

while it would be nice to have a more generic solution, or an API for creating these more generic solutions, a Tox plugin will solve the problem for most people. i guess this can be closed

**Comment by frostming** [comment]
Another reason is Nox doesn't have a good plugin system like tox, I am still studying how to replace the install/run logic or anyone can help contribute a solution.

Close it for now

**Comment by danieleades** [comment]
you might like to take a look at [nox-poetry](https://github.com/cjolowicz/nox-poetry) for reference

**Comment by frostming** [comment]
Haha, I am looking at it right now.

**Comment by frostming** [comment]
It turns out to be much easier to use PDM in nox, here it is:

https://pdm.fming.dev/advanced/#automatic-testing-with-nox

/cc @danieleades @pohlt @pawamoy

**Comment by danieleades** [comment]
that's a really nice solution. very tidy!

**Comment by pohlt** [comment]
Thanks for the hint! Already replaced tox with nox in my small project and it works like a charm (also locally where I had issues with tox using the wrong Python version).

**Comment by patrick91** [comment]
updated link: https://pdm.fming.dev/latest/usage/advanced/#use-nox-as-the-runner

(I was looking for an alternative to https://hatch.pypa.io/latest/config/environment/advanced/#matrix)

**Comment by mforbes** [comment]
@frostming Is there an obvious way to do matrix testing with a bunch of different versions of a dependency (like Sphinx)?  I am looking for two things:

1. A way to install specific versions of a library in the venv before testing/
2. A way to ask `pdm` what versions of a library are supported for a given version of python.

For `nox-poetry` a solution is discussed here:

https://github.com/cjolowicz/nox-poetry/discussions/289

Let me know if I should open a new issue - this seems to be the most relevant current issue though.
