### ISSUE TITLE
Examples how to integrate with CI pipelines (and tox)

### ISSUE THREAD

**Issue by pohlt** [frostming/pdm#281]
## Is your feature request related to a problem? Please describe.

I tried to get pdm working on GitLab's CI (using tox). I have a working solution now, but I'm quite sure it's not using each tool optimally (it was also my _first_ project with _any_ CI, so bear with me. ;-))

## Describe the solution you'd like

I would have appreciated a demo repo on GitLab, GitHub, and Azure which shows how to use pdm in combination with the corresponding CI pipeline (and some best practices using tools like tox or whatever works best with pdm. See, I'm even not sure about this. :-D).

I'd be happy to setup a demo repo on GitLab and - with you guidance - make it the reference repo for pdm on GitLab.

**Comment by frostming** [comment]
Good suggestion, I don't have much experience with tox but I have some projects whose CI are setup with pdm. Take [marko](https://github.com/frostming/marko/blob/master/.github/workflows/ci.yml) for an example. I appreciate a lot if someone volunteers to improve the docs.

**Comment by frostming** [comment]
In case you are interested, I am working out a tox plugin for PDM. Stay tuned: https://github.com/pdm-project/tox-pdm

**Comment by pohlt** [comment]
Sounds great! I'm curious what you come up with.

The more I think about it, the more I realize: Most of my requirements are
covered by the typical CI pipeline configuration and PDM and I don't see a
lot of additional benefit from using tox.
But my build pipelines are still very basic and tox may shine in a more
complex setup.

**Comment by pawamoy** [comment]
IMHO what tools like tox and nox bring is the ability to test against matrices of dependencies versions (not only matrices of OS and Python versions). Using tools like Poetry or PDM makes this difficult because of the way they lock and install. Maybe they should accept constraints upon installation to say "install everything normally, but for Django I want version 2.11.1" (which would be included in the range specified in pyproject.toml of course). Still, matrices tests could not be run in parallel, or at the expense of creating multiple venvs/__pypackages__ (though not an issue in isolated containers in CI).

**Comment by pohlt** [comment]
I can see how tox/nox can help in the cases you mentioned, but it also felt
to me like the dependency handling of nox and PDM interfered and it was not
obvious to me how to make them cooperate nicely.

I felt the same with poetry, so another big plus for PDM could be if the
interaction with tools like nox is done right, whatever that might be.

**Comment by frostming** [comment]
Hey, I just released [tox-pdm](https://pypi.org/p/tox-pdm) and it works like the following:

- `sections` field to specify which dependency group to install, via `pdm install -s <section>`
- `deps` field that will be installed by normal pip to the `__pypackages__` library path, where you can add parametrized dependencies.

In this way, we avoid regenerating the lock file in the testing process. I hope it helps!

**Comment by pohlt** [comment]
Awesome! As soon as the crunch time for my current project is over, I will integrate tox-pdm in my side project and give it a spin.

Thanks for your work!
