### ISSUE TITLE
Support exporting as setup.py

### ISSUE THREAD

**Issue by frostming** [frostming/pdm#289]

**Comment by lazarillo** [comment]
I don't understand why this was closed.  The code clearly says that it is not implemented yet:

```python
def export(project: Project, candidates: list, options: Any | None) -> str:
    raise NotImplementedError()
```

[source](https://github.com/pdm-project/pdm/blob/main/src/pdm/formats/setup_py.py#L63C1-L64C32)

What am I missing?

**Comment by frostming** [comment]
Supporting it is not in the plan.

**Comment by pawamoy** [comment]
It was removed later: https://github.com/pdm-project/pdm/commit/7894d18e8045d37579cc39348dd15c72e444c453#diff-508d4fe890214310b46011513969196b21755b8a9b2019578ad1120787c3dc84

**Comment by frostming** [comment]
Yes, that was an action towards supporting unspecific build backends. Since converting `pyproject.toml`, especially the build config depends on what build backend you are using. PDM doesn't have enough knowledge to convert it.

**Comment by frostming** [comment]
> Should I make a PR to update the docs to clarify this?

Go ahead

**Comment by lazarillo** [comment]
Here it is: https://github.com/pdm-project/pdm/pull/2481
