### ISSUE TITLE
Wheel *.dist-info/WHEEL Generator field report Poetry 2.2.2

### ISSUE THREAD

**Issue by ntninja** [frostming/pdm#330]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

 1. Create a PDM-managed project: `pdm init`
 2. Generate a wheel for it: `pdm build`

## Actual behavior

The *Generator* field in the generated wheel's `*.dist-info/WHEEL` file contains `poetry 2.2.2`.

## Expected behavior

It should probably contain `PDM 1.4.2`.

If it reporting poetry is intentional, feel free to just close this issue and maybe add a short description as to why this is the case to satisfy my curiosity.

## Environment Information

```bash
PDM version:        1.4.2                          
Python Interpreter: /usr/bin/python3.9 (3.9.2)     
Project Root:       /home/alexander/src/flake8-tabs
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.0-5-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 5.10.24-1 (2021-03-19)",
  "python_full_version": "3.9.2",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by ntninja** [comment]
This issue probably belongs in https://github.com/pdm-project/pdm-pep517/ instead.

According to https://github.com/pdm-project/pdm-pep517/blob/master/pdm/pep517/wheel.py it appears as though the value `poetry` is hard-coded, while the `2.2.2` part is actually the current project version – now it makes even less sense than before to me.

**Comment by frostming** [comment]
Nice catch, it is due to a careless mistake. Will fix it shortly in pdm-pep517

Thanks
