### ISSUE TITLE
PDM Clobbering SSH Username

### ISSUE THREAD

**Issue by kevinastone** [frostming/pdm#68]
A requirement of the form `git@server:repo.git` gets translated into `ssh://server/repo.git`, dropping the `git@` username component of the url.  This then fails cloning if the server requires that `git` username (as GitHub does).

The issue is [this line] (specifically `self.url[4:]`) that slices out the username when constructing the `ssh://` url.  You can bypass this errant special casing with an explicit `ssh://` schema (e.g. `ssh://git@server/repo.git`).

[this line]: https://github.com/frostming/pdm/blob/6f32c0130e85d940958fe5f39727749e79258cde/pdm/models/requirements.py#L341

**Comment by frostming** [comment]
Yeah, a bug fix is on the way
